apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespaces: app
spec:
 containers:
 - name: c1
   image: centos
   ports:
   - ContainerPort: 9000
   resources:
     requests:
       memory: "64Mi"
       cpu: "250m"
     limits:
       memory: "128Mi"
       cpu: "500m"
